language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install http://files.openslides.org/Beta/openslides-1.4b1.tar.gz"
  - "pip install django-discover-runner==0.4 Fabric==1.6.0 pep8==1.4.5"
script: "fab travis_ci"
