language: python
sudo: false
cache:
  directories:
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/
python:
  - "3.4"
  - "3.5"
install:
  - "pip install --upgrade setuptools"
  - "pip install openslides==2.1b3"
  # - "pip install --upgrade --requirement requirements.txt"
  - "pip install flake8==3.0.4 isort==4.2.5"
script:
  - "flake8 openslides_csv_export tests"
  - "isort --check-only --recursive openslides_csv_export tests"
  - "PYTHONPATH=.:$PYTHONPATH DJANGO_SETTINGS_MODULE='tests.settings' openslides test"
